version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      # docker_layer_caching: true
    parallelism: 10
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Take this thing into hyperspace
          environment:
            TERM: xterm
          command: |
            # Update needed keys
            curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
            # Spoof the public key
            ssh-keygen -t rsa -N "" -C "spoof@circle" -f "$HOME/.ssh/spoofkey"
            mv "$HOME/.ssh/spoofkey.pub" "$HOME/.ssh/id_rsa.pub"
            # Install bc
            sudo apt-get update -y
            sudo apt-get install -y bc
            # Hyperdrive
            curl -Ls https://github.com/lando/hyperdrive/releases/download/v0.6.1/hyperdrive > /tmp/hyperdrive
            chmod +x /tmp/hyperdrive
            /tmp/hyperdrive -y --name "Lando System" --email landobot@devwithlando.io
            # @TODO: anyway hyperdrive can assert dominance here?
            sudo ln -sf /usr/bin/nodejs /opt/circleci/.nvm/versions/node/v6.1.0/bin/node
            # We need to not enforce ssh for github because this breaks some tests
            git config --global --unset url.ssh://git@github.com.insteadof
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Disable usage and error reporting
          command: |
            # Disable error reporting
            mkdir -p ~/.lando/cache
            echo false > ~/.lando/cache/report_errors
            # Set CI specific config like disabling usage reports
            cp -f ~/project/.circleci/lando.yml ~/project/config.yml
      - run:
          name: Switch lando over to binary built from source
          command: |
            sudo mv -f /usr/local/bin/lando /usr/local/bin/lando.stable
            # sudo ln -sf ~/project/bin/lando.js /usr/local/bin/lando
            yarn pkg:cli
            sudo mv dist/cli/* /usr/local/bin/lando
            ls -lsa /usr/local/bin
            lando version
            lando --experimental
      - run:
          name: Run func test
          no_output_timeout: 15m
          command: |
            yarn generate:tests
            yarn mocha --timeout 900000 $(circleci tests split ~/project/test/split-file.txt)
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
